replicaCount: 1

image:
  repository: containers.renci.org/renci-dot-org/frontend
  tag: latest

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  port: 3000

ingress:
  host: new-rdo.apps.renci.org

